/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tik.tok.toe;

import javax.swing.JOptionPane;

/**
 *
 * @author Umang
 */
public class TicTocToe extends javax.swing.JFrame {
    int turn=2;
    int bused[]={0,0,0,0,0,0,0,0,0};
    int pXwon[]={0,0,0,0,0,0,0,0,0};
    int pOwon[]={0,0,0,0,0,0,0,0,0};
    int pXwon()
    {
        if(pXwon[0]==1 && pXwon[1]==1 && pXwon[2]==1)
        {
            return 1;
        }
        else if(pXwon[3]==1 && pXwon[4]==1 && pXwon[5]==1)
        {
            return 1;
        }
        else if(pXwon[6]==1 && pXwon[7]==1 && pXwon[8]==1)
        {
            return 1;
        }
        else if(pXwon[0]==1 && pXwon[4]==1 && pXwon[8]==1)
        {
            return 1;
        }
        else if(pXwon[2]==1 && pXwon[4]==1 && pXwon[6]==1)
        {
            return 1;
        }
        else if(pXwon[0]==1 && pXwon[3]==1 && pXwon[6]==1)
        {
            return 1;
        }
        else if(pXwon[1]==1 && pXwon[4]==1 && pXwon[7]==1)
        {
            return 1;
        }
        else if(pXwon[2]==1 && pXwon[5]==1 && pXwon[8]==1)
        {
            return 1;
        }
        else{
            return 0;
        }
    }
        int pOwon()
        {
        if(pOwon[0]==1 && pOwon[1]==1 && pOwon[2]==1)
        {
            return 1;
        }
        else if(pOwon[3]==1 && pOwon[4]==1 && pOwon[5]==1)
        {
            return 1;
        }
        else if(pOwon[6]==1 && pOwon[7]==1 && pOwon[8]==1)
        {
            return 1;
        }
        else if(pOwon[0]==1 && pOwon[4]==1 && pOwon[8]==1)
        {
            return 1;
        }
        else if(pOwon[2]==1 && pOwon[4]==1 && pOwon[6]==1)
        {
            return 1;
        }
        else if(pOwon[0]==1 && pOwon[3]==1 && pOwon[6]==1)
        {
            return 1;
        }
        else if(pOwon[1]==1 && pOwon[4]==1 && pOwon[7]==1)
        {
            return 1;
        }
        else if(pOwon[2]==1 && pOwon[5]==1 && pOwon[8]==1)
        {
            return 1;
        }
        else{
            return 0;
        }
        
    }

        public void disable(){
            jTextField1.hide();
        }

    /**
     * Creates new form TicTocToe
     */
    public TicTocToe() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField2 = new javax.swing.JTextField();
        jB6 = new javax.swing.JButton();
        jB5 = new javax.swing.JButton();
        jB4 = new javax.swing.JButton();
        jB1 = new javax.swing.JButton();
        jB2 = new javax.swing.JButton();
        jB9 = new javax.swing.JButton();
        jB8 = new javax.swing.JButton();
        jB7 = new javax.swing.JButton();
        jB3 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();

        jTextField2.setText("jTextField2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jB6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB6ActionPerformed(evt);
            }
        });

        jB5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB5ActionPerformed(evt);
            }
        });

        jB4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB4ActionPerformed(evt);
            }
        });

        jB1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB1ActionPerformed(evt);
            }
        });

        jB2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB2ActionPerformed(evt);
            }
        });

        jB9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB9ActionPerformed(evt);
            }
        });

        jB8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB8ActionPerformed(evt);
            }
        });

        jB7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB7ActionPerformed(evt);
            }
        });

        jB3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB3ActionPerformed(evt);
            }
        });

        jTextField1.setText("jTextField1");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jB7, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jB8, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jB4, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jB5, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jB6, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jB9, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jB1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jB2, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jB3, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(34, 34, 34))
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jB1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jB2, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jB3, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jB6, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jB5, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jB4, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jB9, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jB8, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jB7, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jB3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB3ActionPerformed
          if(bused[2]==0)
        {
        if(turn%2==0){
            turn++;
            jB3.setText("X");
            bused[2]=1;
            pXwon[2]=1;
            
            int result1=pXwon();
            int result2=pOwon();
            if(result1==1){
                JOptionPane.showMessageDialog(rootPane,"Player X Won!!");
            }
            else if(result2==1){
                JOptionPane.showMessageDialog(rootPane,"Player O Won!!");
            }
        }
        else{
            turn++;
            jB3.setText("O");
            bused[2]=1;
            pOwon[2]=1;
            
            int result1=pXwon();
            int result2=pOwon();
            if(result1==1){
                JOptionPane.showMessageDialog(rootPane,"Player X Won!!");
            }
            else if(result2==1){
                JOptionPane.showMessageDialog(rootPane,"Player O Won!!");
            }
        }
        }
        else{
            JOptionPane.showMessageDialog(rootPane,"THIS IS ALREADY USED");
        }
    }//GEN-LAST:event_jB3ActionPerformed

    private void jB2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB2ActionPerformed
     
         if(bused[1]==0)
        {
        if(turn%2==0){
            turn++;
            jB2.setText("X");
            bused[1]=1;
            pXwon[1]=1;
            
            int result1=pXwon();
            int result2=pOwon();
            if(result1==1){
                JOptionPane.showMessageDialog(rootPane,"Player X Won!!");
            }
            else if(result2==1){
                JOptionPane.showMessageDialog(rootPane,"Player O Won!!");
            }
        }
        else{
            turn++;
            jB2.setText("O");
            bused[1]=1;
            pOwon[1]=1;
            
            int result1=pXwon();
            int result2=pOwon();
            if(result1==1){
                JOptionPane.showMessageDialog(rootPane,"Player X Won!!");
            }
            else if(result2==1){
                JOptionPane.showMessageDialog(rootPane,"Player O Won!!");
            }
        }
        }
        else{
            JOptionPane.showMessageDialog(rootPane,"THIS IS ALREADY USED");
        }
   
    }//GEN-LAST:event_jB2ActionPerformed

    private void jB1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB1ActionPerformed
        if(bused[0]==0)
        {
        if(turn%2==0){
            turn++;
            jB1.setText("X");
            bused[0]=1;
            pXwon[0]=1;
            
            int result1=pXwon();
            int result2=pOwon();
            if(result1==1){
                JOptionPane.showMessageDialog(rootPane,"Player X Won!!");
            }
            else if(result2==1){
                JOptionPane.showMessageDialog(rootPane,"Player O Won!!");
            }
        }
        else{
            turn++;
            jB1.setText("O");
            bused[0]=1;
            pOwon[0]=1;
            
            int result1=pXwon();
            int result2=pOwon();
            if(result1==1){
                JOptionPane.showMessageDialog(rootPane,"Player X Won!!");
            }
            else if(result2==1){
                JOptionPane.showMessageDialog(rootPane,"Player O Won!!");
            }
        }
        }
        else{
            JOptionPane.showMessageDialog(rootPane,"THIS IS ALREADY USED");
        }
    }//GEN-LAST:event_jB1ActionPerformed

    private void jB4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB4ActionPerformed
            if(bused[3]==0)
        {
        if(turn%2==0){
            turn++;
            jB4.setText("X");
            bused[3]=1;
            pXwon[3]=1;
            
            int result1=pXwon();
            int result2=pOwon();
            if(result1==1){
                JOptionPane.showMessageDialog(rootPane,"Player X Won!!");
            }
            else if(result2==1){
                JOptionPane.showMessageDialog(rootPane,"Player O Won!!");
            }
        }
        else{
            turn++;
            jB4.setText("O");
            bused[3]=1;
            pOwon[3]=1;
            
            int result1=pXwon();
            int result2=pOwon();
            if(result1==1){
                JOptionPane.showMessageDialog(rootPane,"Player X Won!!");
            }
            else if(result2==1){
                JOptionPane.showMessageDialog(rootPane,"Player O Won!!");
            }
        }
        }
        else{
            JOptionPane.showMessageDialog(rootPane,"THIS IS ALREADY USED");
        }
    }//GEN-LAST:event_jB4ActionPerformed

    private void jB5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB5ActionPerformed
            if(bused[4]==0)
        {
        if(turn%2==0){
            turn++;
            jB5.setText("X");
            bused[4]=1;
            pXwon[4]=1;
            
            int result1=pXwon();
            int result2=pOwon();
            if(result1==1){
                JOptionPane.showMessageDialog(rootPane,"Player X Won!!");
            }
            else if(result2==1){
                JOptionPane.showMessageDialog(rootPane,"Player O Won!!");
            }
        }
        else{
            turn++;
            jB5.setText("O");
            bused[4]=1;
            pOwon[4]=1;
            
            int result1=pXwon();
            int result2=pOwon();
            if(result1==1){
                JOptionPane.showMessageDialog(rootPane,"Player X Won!!");
            }
            else if(result2==1){
                JOptionPane.showMessageDialog(rootPane,"Player O Won!!");
            }
        }
        }
        else{
            JOptionPane.showMessageDialog(rootPane,"THIS IS ALREADY USED");
        }
    }//GEN-LAST:event_jB5ActionPerformed

    private void jB6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB6ActionPerformed
            if(bused[5]==0)
        {
        if(turn%2==0){
            turn++;
            jB6.setText("X");
            bused[5]=1;
            pXwon[5]=1;
            
            int result1=pXwon();
            int result2=pOwon();
            if(result1==1){
                JOptionPane.showMessageDialog(rootPane,"Player X Won!!");
            }
            else if(result2==1){
                JOptionPane.showMessageDialog(rootPane,"Player O Won!!");
            }
        }
        else{
            turn++;
            jB6.setText("O");
            bused[5]=1;
            pOwon[5]=1;
            
            int result1=pXwon();
            int result2=pOwon();
            if(result1==1){
                JOptionPane.showMessageDialog(rootPane,"Player X Won!!");
            }
            else if(result2==1){
                JOptionPane.showMessageDialog(rootPane,"Player O Won!!");
            }
        }
        }
        else{
            JOptionPane.showMessageDialog(rootPane,"THIS IS ALREADY USED");
        }
    }//GEN-LAST:event_jB6ActionPerformed

    private void jB7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB7ActionPerformed
            if(bused[6]==0)
        {
        if(turn%2==0){
            turn++;
            jB7.setText("X");
            bused[6]=1;
            pXwon[6]=1;
            
            int result1=pXwon();
            int result2=pOwon();
            if(result1==1){
                JOptionPane.showMessageDialog(rootPane,"Player X Won!!");
            }
            else if(result2==1){
                JOptionPane.showMessageDialog(rootPane,"Player O Won!!");
            }
        }
        else{
            turn++;
            jB7.setText("O");
            bused[6]=1;
            pOwon[6]=1;
            
            int result1=pXwon();
            int result2=pOwon();
            if(result1==1){
                JOptionPane.showMessageDialog(rootPane,"Player X Won!!");
            }
            else if(result2==1){
                JOptionPane.showMessageDialog(rootPane,"Player O Won!!");
            }
        }
        }
        else{
            JOptionPane.showMessageDialog(rootPane,"THIS IS ALREADY USED");
        }
    }//GEN-LAST:event_jB7ActionPerformed

    private void jB8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB8ActionPerformed
            if(bused[7]==0)
        {
        if(turn%2==0){
            turn++;
            jB8.setText("X");
            bused[7]=1;
            pXwon[7]=1;
            
            int result1=pXwon();
            int result2=pOwon();
            if(result1==1){
                JOptionPane.showMessageDialog(rootPane,"Player X Won!!");
            }
            else if(result2==1){
                JOptionPane.showMessageDialog(rootPane,"Player O Won!!");
            }
        }
        else{
            turn++;
            jB8.setText("O");
            bused[7]=1;
            pOwon[7]=1;
            
            int result1=pXwon();
            int result2=pOwon();
            if(result1==1){
                JOptionPane.showMessageDialog(rootPane,"Player X Won!!");
            }
            else if(result2==1){
                JOptionPane.showMessageDialog(rootPane,"Player O Won!!");
            }
        }
        }
        else{
            JOptionPane.showMessageDialog(rootPane,"THIS IS ALREADY USED");
        }
    }//GEN-LAST:event_jB8ActionPerformed

    private void jB9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB9ActionPerformed
            if(bused[8]==0)
        {
        if(turn%2==0){
            turn++;
            jB9.setText("X");
            bused[8]=1;
            pXwon[8]=1;
            
            int result1=pXwon();
            int result2=pOwon();
            if(result1==1){
                JOptionPane.showMessageDialog(rootPane,"Player X Won!!");
            }
            else if(result2==1){
                JOptionPane.showMessageDialog(rootPane,"Player O Won!!");
            }
        }
        else{
            turn++;
            jB9.setText("O");
            bused[8]=1;
            pOwon[8]=1;
            
            int result1=pXwon();
            int result2=pOwon();
            if(result1==1){
                JOptionPane.showMessageDialog(rootPane,"Player X Won!!");
            }
            else if(result2==1){
                JOptionPane.showMessageDialog(rootPane,"Player O Won!!");
            }
        }
        }
        else{
            JOptionPane.showMessageDialog(rootPane,"THIS IS ALREADY USED");
        }
    }//GEN-LAST:event_jB9ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
        jTextField1 textField = new jTextField1();
textField.set(false);
//jTextField1.setEnabled(false);
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TicTocToe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TicTocToe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TicTocToe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TicTocToe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TicTocToe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jB1;
    private javax.swing.JButton jB2;
    private javax.swing.JButton jB3;
    private javax.swing.JButton jB4;
    private javax.swing.JButton jB5;
    private javax.swing.JButton jB6;
    private javax.swing.JButton jB7;
    private javax.swing.JButton jB8;
    private javax.swing.JButton jB9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
